apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aad-pod-identity
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./aad-pod-identity/production
    repoURL: https://github.com/FutureNHS/futurenhs-deployments.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
