apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-service-operator
spec:
  destination:
    namespace: azure-service-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./azure-service-operator/production
    repoURL: https://github.com/FutureNHS/futurenhs-deployments.git
    targetRevision: master
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      version: v1beta1
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/namespaceSelector/matchExpressions
  syncPolicy:
    automated:
      prune: true
