apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
images:
- digest: sha256:a9b186265ccaa78affc359970ae65a06386f4940e0927e5c965acde14f7b5bea
  name: fnhsproduction.azurecr.io/frontend
