
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLServer
metadata:
  name: postgresqlserver-sample
spec:
  location: westeurope
  resourceGroup: platform-dev-david
  serverVersion: "10"
  sslEnforcement: Enabled
  sku:
    name: B_Gen5_2
    tier: Basic
    family: Gen5
    size: "51200"
    capacity: 2
  # Use the field below to optionally specify a different keyvault 
  # to store the server admin credential secrets in
  #keyVaultToStoreSecrets: asoSecretKeyVault
---
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLDatabase
metadata:
  name: postgresqldatabase-sample
spec:
  resourceGroup: platform-dev-david
  server: postgresqlserver-sample
---
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLFirewallRule
metadata:
  name: postgresqlfirewallrule-sample
spec:
  resourceGroup: platform-dev-david
  server: postgresqlserver-sample
  startIpAddress: 0.0.0.0
  endIpAddress: 0.0.0.0
---
# https://github.com/Azure/azure-service-operator/blob/217c62e5f65c94b753fa62c9a87eda210c1a8e5f/config/samples/azure_v1alpha1_postgresqluser.yaml
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLUser
metadata:
  name: psqluser-sample
spec:
  server: postgresqlserver-sample
  dbName: postgresqldatabase-sample
  resourceGroup: platform-dev-david
  # The Azure Database for PostgreSQL server is created with the 3 default roles defined.
  # azure_pg_admin
  # azure_superuser
  # your server admin user
  roles:
    - "azure_pg_admin"
   # Specify a specific username for the user
  username: psqluser-sample
  # Specify adminSecret and adminSecretKeyVault if you want to 
  # read the PSQL server admin creds from a specific keyvault secret
  # adminSecret: postgresqlserver-sample
  # adminSecretKeyVault: asokeyvault
  
  # Use the field below to optionally specify a different keyvault 
  # to store the secrets in
  # keyVaultToStoreSecrets: asokeyvault
