openapi: "3.0.3"
info:
  version: "1.0.0"
  title: "FutureNHS Events"
paths: {}
components:
  schemas:
    Event:
      oneOf:
        - $ref: "#/components/schemas/LoginFailed"
        - $ref: "#/components/schemas/LoginSuccess"
      discriminator:
        propertyName: eventType
        mapping:
          LoginFailed: "#/components/schemas/LoginFailed"
          LoginSuccess: "#/components/schemas/LoginSuccess"
    LoginFailed:
      type: object
      required:
        - subject
        - eventType
        - data
        - dataVersion
      properties:
        subject:
          type: string
        eventType:
          type: string
        data:
          type: object
          required:
            - messages
          properties:
            messages:
              type: array
              items:
                type: string
        dataVersion:
          type: string
    LoginSuccess:
      type: object
      required:
        - subject
        - eventType
        - data
        - dataVersion
      properties:
        subject:
          type: string
        eventType:
          type: string
        data:
          type: object
        dataVersion:
          type: string
