apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: fnhsproduction.azurecr.io/frontend
          env:
            - name: EVENTGRID_TOPIC_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: frontend
                  key: eventgrid_topic_endpoint
            - name: EVENTGRID_TOPIC_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend
                  key: eventgrid_topic_key
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 30
