[package]
name = "workspace_service"
version = "0.1.0"
edition = "2018"

[dependencies]
dotenv = "0.15.0"
opentelemetry-application-insights = "0.4.0"
opentelemetry = "0.8.0"
sqlx = { git = "https://github.com/frigus02/sqlx", rev = "106a6a83952bfc0e3316d54f99d865e469dcc15a", default-features = false, features = [ "runtime-async-std", "macros", "migrate", "offline", "postgres", "tls","uuid" ]  }
tide = "0.13.0"
tracing = { version = "0.1.19", features = ["attributes"] }
tracing-futures = "0.2.4"
tracing-opentelemetry = "0.7.0"
tracing-subscriber = "0.2.11"
anyhow = "1.0.32"
async-graphql = "1.18.0"
async-graphql-tide = "1.17.9"
async-std = { version = "1.6.3", features = ["attributes", "unstable"] }
uuid = "0.8.1"
http-types = "2.4.0"
