/* tslint:disable */
/* eslint-disable */
/**
 * FutureNHS Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LoginFailed,
    LoginSuccess,
    LoginFailedFromJSONTyped,
    LoginFailedToJSON,
    LoginSuccessFromJSONTyped,
    LoginSuccessToJSON,
} from './';

/**
 * @type Event
 * 
 * @export
 */
export type Event = { eventType: 'LoginFailed' } & LoginFailed | { eventType: 'LoginSuccess' } & LoginSuccess;

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['eventType']) {
        case 'LoginFailed':
            return {...LoginFailedFromJSONTyped(json, true), eventType: 'LoginFailed'};
        case 'LoginSuccess':
            return {...LoginSuccessFromJSONTyped(json, true), eventType: 'LoginSuccess'};
        default:
            throw new Error(`No variant of Event exists with 'eventType=${json['eventType']}'`);
    }
}

export function EventToJSON(value?: Event | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['eventType']) {
        case 'LoginFailed':
            return LoginFailedToJSON(value);
        case 'LoginSuccess':
            return LoginSuccessToJSON(value);
        default:
            throw new Error(`No variant of Event exists with 'eventType=${value['eventType']}'`);
    }
}

