/* tslint:disable */
/* eslint-disable */
/**
 * FutureNHS Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginFailedData
 */
export interface LoginFailedData {
    /**
     * 
     * @type {Array<string>}
     * @memberof LoginFailedData
     */
    messages: Array<string>;
}

export function LoginFailedDataFromJSON(json: any): LoginFailedData {
    return LoginFailedDataFromJSONTyped(json, false);
}

export function LoginFailedDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginFailedData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'messages': json['messages'],
    };
}

export function LoginFailedDataToJSON(value?: LoginFailedData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'messages': value.messages,
    };
}


