/* tslint:disable */
/* eslint-disable */
/**
 * FutureNHS Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginSuccess
 */
export interface LoginSuccess {
    /**
     * 
     * @type {string}
     * @memberof LoginSuccess
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof LoginSuccess
     */
    eventType: string;
    /**
     * 
     * @type {object}
     * @memberof LoginSuccess
     */
    data: object;
    /**
     * 
     * @type {string}
     * @memberof LoginSuccess
     */
    dataVersion: string;
}

export function LoginSuccessFromJSON(json: any): LoginSuccess {
    return LoginSuccessFromJSONTyped(json, false);
}

export function LoginSuccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginSuccess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'eventType': json['eventType'],
        'data': json['data'],
        'dataVersion': json['dataVersion'],
    };
}

export function LoginSuccessToJSON(value?: LoginSuccess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subject': value.subject,
        'eventType': value.eventType,
        'data': value.data,
        'dataVersion': value.dataVersion,
    };
}


