/* tslint:disable */
/* eslint-disable */
/**
 * FutureNHS Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LoginFailedData,
    LoginFailedDataFromJSON,
    LoginFailedDataFromJSONTyped,
    LoginFailedDataToJSON,
} from './';

/**
 * 
 * @export
 * @interface LoginFailed
 */
export interface LoginFailed {
    /**
     * 
     * @type {string}
     * @memberof LoginFailed
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof LoginFailed
     */
    eventType: string;
    /**
     * 
     * @type {LoginFailedData}
     * @memberof LoginFailed
     */
    data: LoginFailedData;
    /**
     * 
     * @type {string}
     * @memberof LoginFailed
     */
    dataVersion: string;
}

export function LoginFailedFromJSON(json: any): LoginFailed {
    return LoginFailedFromJSONTyped(json, false);
}

export function LoginFailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginFailed {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'eventType': json['eventType'],
        'data': LoginFailedDataFromJSON(json['data']),
        'dataVersion': json['dataVersion'],
    };
}

export function LoginFailedToJSON(value?: LoginFailed | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subject': value.subject,
        'eventType': value.eventType,
        'data': LoginFailedDataToJSON(value.data),
        'dataVersion': value.dataVersion,
    };
}


