apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: favouritecuisine
  namespace: hello-world
spec:
  encryptedData:
    favouritecuisine: AgCHFk/5MdGteCydzqJ4IFMatjH5t9pLzdiu/A48xD/XS1pKWvJg6cyvKM9Y5+UZJhQj2r9xGn46nnPm1GeZS8Y2UK3Li2txnHnajQ/Ae2mW1V82zsV0Lg4QIhIxpMP8VGOMSjJl49w8x8njxqqSuLK4UwIfclUZLKKbJTzpy1ZarJe1spZ35sRIqxloGgYTH8Rd5jVgFtp8gEP4FT4Xon/rHptJwoac1OAYYNiX1YFdntGMglfb38oBFI6PN9ACvVGUBcRuTINg4mO5p5NRaeRhu4UluBbe1p5nmUPD7JCZSIGcxuJUDfVICZAQ6879Zu2l++VGSJj77H4wvVD3hAlE+ryupNI/T0Lgt2yrptF3FP8kC4VeNogWWz1vxjW2B7Wz5jobBx8qzOPt66mFJs6WeCrwnlejLiBdniHpK7Jw6Uuowexo3zHn2huEtd6ZBIXCp7QG1GpVet2xNKa+OAfUxgJE7u5h9E0P+I+D96WC5NIrvJ77dAGxg9NKTpENS7Pe7X7Tv86TnnvAA2DVTC92BReFs7dwBv8xbptmil9s7qWsavxZ1lcrSOUNVCd+h7YmmpTmLSobjR9naNJFRw5NaeJj5gOXNypRU69LZF3yhGCvaAsap2h4lQRnshQ6As2tCz/D//JNpdsVEXxAvqhp5LrQQK4JoS8CaQgILF7ToNNusSbZx1VlYsFhdrGJmokpwpCq0lI=
  template:
    metadata:
      creationTimestamp: null
      name: favouritecuisine
      namespace: hello-world

