apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLServer
metadata:
  name: postgresqlserver-hello-world
  namespace: hello-world
spec:
  resourceGroup: platform-dev-$NAME
---
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLDatabase
metadata:
  name: postgresqldatabase-hello-world
  namespace: hello-world
spec:
  resourceGroup: platform-dev
---
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLUser
metadata:
  name: psqluser-hello-world
  namespace: hello-world
spec:
  resourceGroup: platform-dev
