/*
 * FutureNHS Events
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "eventtype")]
pub enum Event {
    #[serde(rename="LoginFailed")]
    LoginFailed {
        #[serde(rename = "subject")]
        subject: String,
        #[serde(rename = "data")]
        data: crate::models::LoginFailedData,
        #[serde(rename = "dataVersion")]
        data_version: String,
    },
    #[serde(rename="LoginSuccess")]
    LoginSuccess {
        #[serde(rename = "subject")]
        subject: String,
        #[serde(rename = "data")]
        data: serde_json::Value,
        #[serde(rename = "dataVersion")]
        data_version: String,
    },
}




