/*
 * FutureNHS Events
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginFailed {
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "data")]
    pub data: crate::models::LoginFailedData,
    #[serde(rename = "dataVersion")]
    pub data_version: String,
}

impl LoginFailed {
    pub fn new(subject: String, event_type: String, data: crate::models::LoginFailedData, data_version: String) -> LoginFailed {
        LoginFailed {
            subject,
            data,
            data_version,
        }
    }
}


