/*
 * FutureNHS Events
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginSuccess {
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "data")]
    pub data: serde_json::Value,
    #[serde(rename = "dataVersion")]
    pub data_version: String,
}

impl LoginSuccess {
    pub fn new(subject: String, event_type: String, data: serde_json::Value, data_version: String) -> LoginSuccess {
        LoginSuccess {
            subject,
            data,
            data_version,
        }
    }
}


