name: frontend-master

on:
  push:
    branches:
      - master
    paths:
      - frontend/**
      - .github/workflows/frontend-master.yml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-platform
          path: futurenhs-platform
          token: ${{secrets.DEPLOYMENT_TOKEN}}
      - name: "Login to docker"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: "Build & Push image"
        run: |
          cd $GITHUB_WORKSPACE/futurenhs-platform/frontend
          TAG="$(git rev-parse --short=7 ${{ github.sha }})"
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${TAG}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${TAG}
          DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${TAG})"
          echo ::set-env name=TAG::$TAG
          echo ::set-env name=DIGEST::$DIGEST

      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-deployments
          path: futurenhs-deployments
          token: ${{secrets.DEPLOYMENT_TOKEN}}

      - name: Copy deployment.yml
        run: |
          set -eux

          cd $GITHUB_WORKSPACE/futurenhs-platform/frontend/manifests
          cp deployment.yml kustomization.yaml $GITHUB_WORKSPACE/futurenhs-deployments/

      - name: Update image tag and deploy
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 3.5.5
          command: |
            set -eux
            cd $GITHUB_WORKSPACE/futurenhs-deployments

            kustomize edit set image $DIGEST
            # TODO create service account, swap out email, update deployment_token secret
            git config --local user.email "tracy.wu@red-badger.com"
            git config --local user.name "FutureNHS CI/CD"
            git add -A
            git diff-index --quiet HEAD || git commit -am "CI: Update production image for ${TAG}"

            declare -i n
            n=0
            until [ $n -ge 5 ]
            do
              git push && break
              n+=1
              git pull --rebase
            done
