name: frontend-branch

on:
  pull_request:
    branches:
      - master
    paths:
      - frontend/**
      - event-models/**
      - workspace-service/graphql-schema.json
      - infrastructure/dev-overlay-variables.json
      - .github/workflows/frontend-branch.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ENV
        run: env

      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform

      - name: "Login to docker"
        if: github.base_ref == null && github.head_ref == null
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Run cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: futurenhs-platform/frontend
          start: yarn dev
          wait-on: http://localhost:3000
        env:
          WORKSPACE_SERVICE_GRAPHQL_ENDPOINT: http://localhost:3001/graphql

      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v2.2.0
        if: failure()
        with:
          name: frontend-cypress-screenshots
          path: futurenhs-platform/frontend/cypress/screenshots

      - name: Upload cypress videos
        uses: actions/upload-artifact@v2.2.0
        if: failure()
        with:
          name: frontend-cypress-videos
          path: futurenhs-platform/frontend/cypress/videos

      - name: "Build image"
        working-directory: futurenhs-platform/frontend
        run: |
          TAG="$(git rev-parse --short=7 ${{ github.sha }})"
          echo "TAG=$TAG" >>$GITHUB_ENV
          make docker-build tag=${TAG}

      - name: Test dev overlay creation
        run: $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/scripts/create-dev-overlays.py

      - name: "Push image"
        if: env.GITHUB_HEAD_REF == null && env.GITHUB_BASE_REF == null
        working-directory: futurenhs-platform/frontend
        run: |
          make docker-push tag=${TAG}
          DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${TAG})"
          echo "DIGEST=$DIGEST" >>$GITHUB_ENV

      - name: Clone Deployments repo
        if: env.GITHUB_HEAD_REF == null && env.GITHUB_BASE_REF == null
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-deployments
          path: futurenhs-deployments
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout the correct Deployments repo branch
        if: env.GITHUB_HEAD_REF == null && env.GITHUB_BASE_REF == null
        working-directory: futurenhs-deployments
        run: |
          set -eux
          git config --local user.email "futurenhs-devs@red-badger.com"
          git config --local user.name "FutureNHS CI/CD"
          if git fetch --unshallow origin pr-$GITHUB_HEAD_REF master ; then
            git checkout origin/pr-$GITHUB_HEAD_REF -b pr-$GITHUB_HEAD_REF
            git merge origin/master --strategy=recursive --strategy-option=ours
          else
            git checkout HEAD -b pr-$GITHUB_HEAD_REF
          fi

      - name: Prepare and copy manifests
        if: env.GITHUB_HEAD_REF == null && env.GITHUB_BASE_REF == null
        run: |
          set -eux

          cd $HOME
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

          # it might actually be possible to kustomize the production version
          # and let the other overlays pick up the change.
          cd $GITHUB_WORKSPACE/futurenhs-platform/frontend/manifests/dev-template
          $HOME/kustomize edit set image $DIGEST

          $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/scripts/create-dev-overlays.py
          # TODO: would be nice if the deployments repo followed the same structure
          # as the platform repo, but only contained manifests.
          mkdir -p $GITHUB_WORKSPACE/futurenhs-deployments/frontend
          cp -r $GITHUB_WORKSPACE/futurenhs-platform/frontend/manifests/* $GITHUB_WORKSPACE/futurenhs-deployments/frontend

      - name: Deploy
        if: env.GITHUB_HEAD_REF == null && env.GITHUB_BASE_REF == null
        working-directory: futurenhs-deployments
        run: |
          set -eux

          git add -A
          # TODO: can we make this commit message reflect the message at the tip of the platform repo?
          git diff-index --quiet HEAD || git commit -am "CI: Update dev image for ${TAG}"

          declare -i n
          n=0
          until [ $n -ge 5 ]
          do
            git push origin "HEAD:pr-$GITHUB_HEAD_REF" && break
            n+=1
            git fetch origin pr-$GITHUB_HEAD_REF
            git merge origin/pr-$GITHUB_HEAD_REF --strategy=recursive --strategy-option=ours
          done

          if [ $n -ge 5 ]
          then
            echo "ran out of retries"
            exit 1
          fi
