name: frontend-branch

on:
  pull_request:
    branches:
      - master
    paths:
      - frontend/**
      - event-models/**
      - workspace-service/graphql-schema.json
      - infrastructure/dev-overlay-variables.json
      - .github/workflows/frontend-branch.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ENV
        run: env

      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform

      - name: Run cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: futurenhs-platform/frontend
          start: yarn dev
          wait-on: http://localhost:3000
        env:
          WORKSPACE_SERVICE_GRAPHQL_ENDPOINT: http://localhost:3001/graphql

      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v2.2.0
        if: failure()
        with:
          name: frontend-cypress-screenshots
          path: futurenhs-platform/frontend/cypress/screenshots

      - name: Upload cypress videos
        uses: actions/upload-artifact@v2.2.0
        if: failure()
        with:
          name: frontend-cypress-videos
          path: futurenhs-platform/frontend/cypress/videos

      - name: "Build image"
        working-directory: futurenhs-platform/frontend
        run: |
          TAG="$(git rev-parse --short=7 ${{ github.sha }})"
          echo "TAG=$TAG" >>$GITHUB_ENV
          make docker-build tag=${TAG}

      - name: Test dev overlay creation
        run: $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/scripts/create-dev-overlays.py

      - name: "Login to docker"
        if: github.base_ref == null && github.head_ref == null
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Push image"
        if: github.base_ref == null && github.head_ref == null
        working-directory: futurenhs-platform/frontend
        run: |
          make docker-push tag=${TAG}
          DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${TAG})"
          echo "DIGEST=$DIGEST" >>$GITHUB_ENV

      - name: Clone Deployments repo
        if: github.base_ref == null && github.head_ref == null
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-deployments
          path: futurenhs-deployments
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy
        if: github.base_ref == null && github.head_ref == null
        run: $GITHUB_WORKSPACE/futurenhs-platform/.github/workflows/deploy-branch.sh frontend
