name: hello-world-branch

on:
  pull_request:
    branches:
      - master
    paths:
      - hello-world/**
      - .github/workflows/hello-world-branch.yaml

env:
  IMAGE: fnhsproduction.azurecr.io/platform/hello-world

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Login to docker"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: "Build & Push image"
        run: |
          cd $GITHUB_WORKSPACE/futurenhs-platform/hello-world
          TAG="$(git rev-parse --short=7 ${{ github.sha }})"
          make docker-build tag=${TAG}
          make docker-push tag=${TAG}
          DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.REGISTRY_LOGIN_SERVER }}/hello-world:${TAG})"
          echo ::set-env name=TAG::$TAG
          echo ::set-env name=DIGEST::$DIGEST
      - name: Test dev overlay creation
        run: |
          cd $HOME
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          cd $GITHUB_WORKSPACE/futurenhs-deployments/hello-world/dev-template

          $HOME/kustomize edit set image $DIGEST
          infrastructure/scripts/create-dev-overlays.py

      - name: Clone Deployments repo (RACY - MUST HAPPEN AFTER infrastructure-branch ACTION)
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-deployments
          ref: pr-${{ env.GITHUB_HEAD_REF }}
          path: futurenhs-deployments
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Copy manifests
        run: |
          set -eux
          $GITHUB_WORKSPACE/futurenhs-platform/infrastructure/scripts/create-dev-overlays.py
          mkdir -p $GITHUB_WORKSPACE/futurenhs-deployments/hello-world
          cp -r $GITHUB_WORKSPACE/futurenhs-platform/hello-world/manifests/* $GITHUB_WORKSPACE/futurenhs-deployments/hello-world

      - name: Deploy
        run: |
          set -eux

          cd $GITHUB_WORKSPACE/futurenhs-deployments

          git config --local user.email "futurenhs-devs@red-badger.com"
          git config --local user.name "FutureNHS CI/CD"

          git add -A
          # FIXME: can we make this commit message reflect the message at the tip of the platform repo?
          git diff-index --quiet HEAD || git commit -am "CI: Update dev image for ${TAG}"

          declare -i n
          n=0
          until [ $n -ge 5 ]
          do
            # TODO: also push to pr-$GITHUB_ACTOR branch. Can do this as a force-push at the end?
            git push "HEAD:pr-$GITHUB_HEAD_REF" && break
            n+=1
            git pull --rebase
          done