name: infrastructure-branch

on:
  pull_request:
    branches:
      - master
    paths:
      - infrastructure/**
      - .github/workflows/infrastructure-branch.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform

      - uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.13.4

      - name: Validate Terraform of dev environment
        working-directory: futurenhs-platform/infrastructure/environments/dev
        run: |
          set -euxo pipefail
          terraform init -backend=false
          terraform validate

      - name: Validate Terraform of shared dev environment
        working-directory: futurenhs-platform/infrastructure/environments/shared-dev
        run: |
          set -euxo pipefail
          terraform init -backend=false
          terraform validate

      - name: Validate Terraform of production environment
        working-directory: futurenhs-platform/infrastructure/environments/production
        run: |
          set -euxo pipefail
          terraform init -backend=false
          terraform validate

      - name: Clone Deployments repo
        if: secrets.DEPLOY_KEY != null
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-deployments
          path: futurenhs-deployments
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy
        if: secrets.DEPLOY_KEY != null
        run: $GITHUB_WORKSPACE/futurenhs-platform/.github/workflows/deploy-branch.sh infrastructure
