name: infrastructure-master

on:
  push:
    branches:
      - master
    paths:
      - infrastructure/**
      - .github/workflows/infrastructure-master.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Platform repo
        uses: actions/checkout@v2
        with:
          path: futurenhs-platform

      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: FutureNHS/futurenhs-deployments
          path: futurenhs-deployments
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy
        run: $GITHUB_WORKSPACE/futurenhs-platform/.github/workflows/deploy-master.sh infrastructure
